import React from 'react';
import { View, Text } from 'react-native';
import Markdown from 'react-native-markdown-view';

const Attribution = () => (
  <View>
    <Markdown>
      {`
| Department | Related to | Name                                      | License period | Material not material | License type | Link                                                                     | Remote version | Installed version | Defined version | Author                                                                                             |
| :--------- | :--------- | :---------------------------------------- | :------------- | :-------------------- | :----------- | :----------------------------------------------------------------------- | :------------- | :---------------- | :-------------- | :------------------------------------------------------------------------------------------------- |
| kessler    | stuff      | @expo/webpack-config                      | perpetual      | material              | MIT          | git+https://github.com/expo/expo-cli.git                                 | 0.17.3         | 0.17.2            | ^0.17.2         | n/a                                                                                                |
| kessler    | stuff      | @firebase/auth                            | perpetual      | material              | Apache-2.0   | git+https://github.com/firebase/firebase-js-sdk.git                      | 0.16.8         | 0.16.8            | ^0.16.8         | Firebase <firebase-support@google.com> (https://firebase.google.com/)                              |
| kessler    | stuff      | @firebase/firestore                       | perpetual      | material              | Apache-2.0   | git+https://github.com/firebase/firebase-js-sdk.git                      | 2.4.1          | 2.4.1             | ^2.4.1          | Firebase <firebase-support@google.com> (https://firebase.google.com/)                              |
| kessler    | stuff      | @react-native-async-storage/async-storage | perpetual      | material              | MIT          | git+https://github.com/react-native-async-storage/async-storage.git      | 1.17.11        | 1.17.10           | ^1.17.10        | Krzysztof Borowy <hello@krizzu.dev>                                                                |
| kessler    | stuff      | @react-native-masked-view/masked-view     | perpetual      | material              | MIT          | git+https://github.com/react-native-masked-view/masked-view.git          | 0.2.7          | 0.2.7             | 0.2.7           | Mike Nedosekin <crespo8800@gmail.com>                                                              |
| kessler    | stuff      | @react-navigation/bottom-tabs             | perpetual      | material              | MIT          | git+https://github.com/react-navigation/react-navigation.git             | 5.11.15        | 5.11.15           | ^5.11.15        | n/a                                                                                                |
| kessler    | stuff      | @react-navigation/native                  | perpetual      | material              | MIT          | git+https://github.com/react-navigation/react-navigation.git             | 5.9.8          | 5.9.8             | ^5.9.8          | n/a                                                                                                |
| kessler    | stuff      | @react-navigation/stack                   | perpetual      | material              | MIT          | git+https://github.com/react-navigation/react-navigation.git             | 5.14.9         | 5.14.9            | ^5.14.9         | n/a                                                                                                |
| kessler    | stuff      | expo                                      | perpetual      | material              | MIT          | git+https://github.com/expo/expo.git                                     | 46.0.17        | 46.0.16           | ~46.0.16        | Expo                                                                                               |
| kessler    | stuff      | expo-dev-client                           | perpetual      | material              | MIT          | git+https://github.com/expo/expo.git                                     | 1.3.1          | 1.3.1             | ~1.3.1          | 650 Industries, Inc.                                                                               |
| kessler    | stuff      | expo-status-bar                           | perpetual      | material              | MIT          | git+https://github.com/expo/expo.git                                     | 1.4.0          | 1.4.0             | 1.4.0           | 650 Industries, Inc.                                                                               |
| kessler    | stuff      | firebase                                  | perpetual      | material              | Apache-2.0   | git+https://github.com/firebase/firebase-js-sdk.git                      | 7.24.0         | 7.24.0            | ^7.24.0         | Firebase <firebase-support@google.com> (https://firebase.google.com/)                              |
| kessler    | stuff      | lodash                                    | perpetual      | material              | MIT          | git+https://github.com/lodash/lodash.git                                 | 4.17.21        | 4.17.21           | ^4.17.21        | John-David Dalton <john.david.dalton@gmail.com>                                                    |
| kessler    | stuff      | prop-types                                | perpetual      | material              | MIT          | git+https://github.com/facebook/prop-types.git                           | 15.8.1         | 15.8.1            | ^15.8.1         | n/a                                                                                                |
| kessler    | stuff      | react                                     | perpetual      | material              | MIT          | git+https://github.com/facebook/react.git                                | 18.0.0         | 18.0.0            | 18.0.0          | n/a                                                                                                |
| kessler    | stuff      | react-dom                                 | perpetual      | material              | MIT          | git+https://github.com/facebook/react.git                                | 18.0.0         | 18.0.0            | 18.0.0          | n/a                                                                                                |
| kessler    | stuff      | react-native                              | perpetual      | material              | MIT          | git+https://github.com/facebook/react-native.git                         | 0.69.6         | 0.69.6            | 0.69.6          | n/a                                                                                                |
| kessler    | stuff      | react-native-draggable-flatlist           | perpetual      | material              | MIT          | git+https://github.com/computerjazz/react-native-draggable-flatlist.git  | 3.1.2          | 3.1.2             | ^3.1.2          | Daniel Merrill                                                                                     |
| kessler    | stuff      | react-native-gesture-handler              | perpetual      | material              | MIT          | git+https://github.com/software-mansion/react-native-gesture-handler.git | 2.5.0          | 2.5.0             | 2.5.0           | Krzysztof Magiera krzys.magiera@gmail.com                                                          |
| kessler    | stuff      | react-native-markdown-display-updated     | perpetual      | material              | MIT          | git+https://github.com/willmac321/react-native-markdown-display.git      | 7.0.0          | 7.0.0             | ^7.0.0          | Will MacIntyre (this fork only) and Mient-jan Stelling and Tom Pickard + others from the community |
| kessler    | stuff      | react-native-markdown-view                | perpetual      | material              | MIT          | n/a                                                                      | n/a            | 7.0.0-alpha.2     | n/a             | Mient-jan Stelling and Tom Pickard + others from the community                                     |
| kessler    | stuff      | react-native-paper                        | perpetual      | material              | MIT          | git+https://github.com/callstack/react-native-paper.git                  | 4.12.5         | 4.12.5            | ^4.12.5         |                                                                                                    |
| kessler    | stuff      | react-native-reanimated                   | perpetual      | material              | MIT          | git+https://github.com/software-mansion/react-native-reanimated.git      | 2.9.1          | 2.9.1             | ~2.9.1          | Krzysztof Magiera krzys.magiera@gmail.com                                                          |
| kessler    | stuff      | react-native-safe-area-context            | perpetual      | material              | MIT          | git+https://github.com/th3rdwave/react-native-safe-area-context.git      | 4.3.1          | 4.3.1             | 4.3.1           | Janic Duplessis <janicduplessis@gmail.com>                                                         |
| kessler    | stuff      | react-native-screens                      | perpetual      | material              | MIT          | git+https://github.com/software-mansion/react-native-screens.git         | 3.15.0         | 3.15.0            | 3.15.0          | Krzysztof Magiera krzys.magiera@gmail.com                                                          |
| kessler    | stuff      | react-native-svg                          | perpetual      | material              | MIT          | git+https://github.com/react-native-community/react-native-svg.git       | 12.3.0         | 12.3.0            | 12.3.0          | n/a                                                                                                |
| kessler    | stuff      | react-native-web                          | perpetual      | material              | MIT          | git://github.com/necolas/react-native-web.git                            | 0.18.7         | 0.18.7            | 0.18.7          | Nicolas Gallagher                                                                                  |
| kessler    | stuff      | react-redux                               | perpetual      | material              | MIT          | git+https://github.com/reduxjs/react-redux.git                           | 7.2.9          | 7.2.9             | ^7.2.6          | Dan Abramov <dan.abramov@me.com> (https://github.com/gaearon)                                      |
| kessler    | stuff      | @babel/core                               | perpetual      | material              | MIT          | https://github.com/babel/babel.git                                       | 7.20.2         | 7.19.3            | ^7.12.9         | The Babel Team (https://babel.dev/team)                                                            |
| kessler    | stuff      | eslint                                    | perpetual      | material              | MIT          | git+https://github.com/eslint/eslint.git                                 | 7.32.0         | 7.32.0            | ^7.32.0         | Nicholas C. Zakas <nicholas+npm@nczconsulting.com>                                                 |
| kessler    | stuff      | eslint-config-airbnb                      | perpetual      | material              | MIT          | git+https://github.com/airbnb/javascript.git                             | 18.2.1         | 18.2.1            | ^18.2.1         | Jake Teton-Landis (https://twitter.com/@jitl)                                                      |
| kessler    | stuff      | eslint-config-prettier                    | perpetual      | material              | MIT          | git+https://github.com/prettier/eslint-config-prettier.git               | 7.2.0          | 7.2.0             | ^7.2.0          | Simon Lydell                                                                                       |
| kessler    | stuff      | eslint-import-resolver-node               | perpetual      | material              | MIT          | git+https://github.com/import-js/eslint-plugin-import.git                | 0.3.6          | 0.3.6             | ^0.3.6          | Ben Mosher (me@benmosher.com)                                                                      |
| kessler    | stuff      | eslint-plugin-import                      | perpetual      | material              | MIT          | git+https://github.com/import-js/eslint-plugin-import.git                | 2.26.0         | 2.26.0            | ^2.25.4         | Ben Mosher <me@benmosher.com>                                                                      |
| kessler    | stuff      | eslint-plugin-jsx-a11y                    | perpetual      | material              | MIT          | git+https://github.com/jsx-eslint/eslint-plugin-jsx-a11y.git             | 6.6.1          | 6.6.1             | ^6.5.1          | Ethan Cohen                                                                                        |
| kessler    | stuff      | eslint-plugin-prettier                    | perpetual      | material              | MIT          | git+https://github.com/prettier/eslint-plugin-prettier.git               | 3.4.1          | 3.4.1             | ^3.4.1          | Teddy Katz                                                                                         |
| kessler    | stuff      | eslint-plugin-react                       | perpetual      | material              | MIT          | git+https://github.com/jsx-eslint/eslint-plugin-react.git                | 7.31.10        | 7.31.10           | ^7.28.0         | Yannick Croissant <yannick.croissant+npm@gmail.com>                                                |
| kessler    | stuff      | eslint-plugin-react-hooks                 | perpetual      | material              | MIT          | git+https://github.com/facebook/react.git                                | 4.6.0          | 4.6.0             | ^4.3.0          | n/a                                                                                                |
| kessler    | stuff      | prettier                                  | perpetual      | material              | MIT          | git+https://github.com/prettier/prettier.git                             | 2.7.1          | 2.7.1             | ^2.5.1          | James Long                                                                                         |

`}
</Markdown>
</View>
);

export default Attribution;
